# -*- coding: utf-8 -*-
"""Pension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnb-VR1IE24VWKdEf7WWuQNulWoxHxlG
"""

# @title מחשבון פנסיה מתקדם - פרישה בגיל 67
import matplotlib.pyplot as plt
import numpy as np

# @markdown הכנס את הנתונים שלך כאן:
גיל_נוכחי = 46  # @param {type:"integer"}
צבירה_קיימת = 1800000  # @param {type:"number"}
הפקדה_חודשית = 7800  # @param {type:"number"}
תשואה_שנתית_אחוזים = 5  # @param {type:"number"}
אינפלציה_שנתית_חזויה = 1.9  # @param {type:"number"}
מקדם_אקטוארי_חזוי = 203.2 # @param {type:"number"}

def calculate_pension_colab(current_age, balance, monthly_dep, annual_return_pct, inflation_pct, manual_coefficient):
    retire_age = 67
    years_to_retire = retire_age - current_age

    if years_to_retire <= 0:
        print("שגיאה: הגיל חייב להיות נמוך מ-67")
        return

    annual_return = annual_return_pct / 100
    monthly_return = annual_return / 12
    months = years_to_retire * 12

    # חישוב מסלול צבירה לגרף
    balances = []
    current_bal = balance
    for m in range(months + 1):
        balances.append(current_bal)
        current_bal = current_bal * (1 + monthly_return) + monthly_dep

    future_balance = balances[-1]
    projected_coefficient = manual_coefficient
    gross_pension_fund = future_balance / projected_coefficient
    national_insurance = 2300
    total_gross = gross_pension_fund + national_insurance

    # חישוב מס
    taxable_income = max(0, gross_pension_fund - 4500)
    if taxable_income <= 6790:
        tax = taxable_income * 0.10
    elif taxable_income <= 9730:
        tax = (6790 * 0.10) + (taxable_income - 6790) * 0.14
    else:
        tax = (6790 * 0.10) + (2940 * 0.14) + (taxable_income - 9730) * 0.20

    tax = max(0, tax - 570)
    health_tax = 116
    net_pension = total_gross - tax - health_tax
    real_value_net = net_pension / ((1 + (inflation_pct / 100)) ** years_to_retire)

    # הדפסת נתונים מפורטת (כפי שהיה בגרסה הקודמת)
    print("="*40)
    print(f" תמצית תחזית פרישה לגיל {retire_age}")
    print("="*40)
    print(f"צבירה צפויה בפרישה (נומינלי): {future_balance:,.0f} ₪")
    print(f"מקדם אקטוארי בשימוש: {projected_coefficient:.1f}")
    print("-"*40)
    print(f"קצבת פנסיה (ברוטו): {gross_pension_fund:,.0f} ₪")
    print(f"קצבת ביטוח לאומי: {national_insurance:,.0f} ₪")
    print(f"מס הכנסה משוער: {tax:,.0f} ₪")
    print(f"דמי בריאות: {health_tax} ₪")
    print("-"*40)
    print(f"סה\"כ הכנסה נטו (נומינלי): {net_pension:,.0f} ₪")
    print(f"ערך ריאלי (במונחי כוח קנייה של היום): {real_value_net:,.0f} ₪")
    print("="*40)
    print(f"* מבוסס על אינפלציה שנתית ממוצעת של {inflation_pct}%")

    # יצירת גרפים
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    # גרף 1: צמיחת הון
    years = np.linspace(current_age, retire_age, len(balances))
    ax1.plot(years, balances, color='blue', linewidth=2)
    ax1.fill_between(years, balances, color='skyblue', alpha=0.3)
    ax1.set_title("צמיחת צבירה פנסיונית לאורך זמן")
    ax1.set_xlabel("גיל")
    ax1.set_ylabel("₪ סכום בצבירה")
    ax1.grid(True, linestyle='--', alpha=0.6)

    # גרף 2: התפלגות קצבה
    labels = ['נטו פנסיה', 'ביטוח לאומי', 'מס הכנסה', 'דמי בריאות']
    sizes = [gross_pension_fund - tax - health_tax, national_insurance, tax, health_tax]
    colors = ['#66b3ff','#99ff99','#ff9999','#ffcc99']
    ax2.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=colors)
    ax2.set_title("התפלגות קצבה חודשית ברוטו")

    plt.tight_layout()
    plt.show()

# הרצת החישוב
calculate_pension_colab(גיל_נוכחי, צבירה_קיימת, הפקדה_חודשית, תשואה_שנתית_אחוזים, אינפלציה_שנתית_חזויה, מקדם_אקטוארי_חזוי)


# @title מחשבון פנסיה מתקדם - פרישה בגיל 67 (תיקון עברית סופי + פירוט מלא)
import matplotlib.pyplot as plt
import numpy as np
import arabic_reshaper
from bidi.algorithm import get_display

# פונקציית עזר לתיקון עברית בגרפים
def fix_heb(text):
    if not text: return text
    reshaped_text = arabic_reshaper.reshape(str(text))
    return get_display(reshaped_text)

# @markdown הכנס את הנתונים שלך כאן:
גיל_נוכחי = 46  # @param {type:"integer"}
צבירה_קיימת = 1800000  # @param {type:"number"}
הפקדה_חודשית = 7800  # @param {type:"number"}
תשואה_שנתית_אחוזים = 4.5  # @param {type:"number"}
אינפלציה_שנתית_חזויה = 1.9  # @param {type:"number"}
מקדם_אקטוארי_חזוי = 203.2 # @param {type:"number"}

def calculate_pension_colab(current_age, balance, monthly_dep, annual_return_pct, inflation_pct, manual_coefficient):
    retire_age = 67
    years_to_retire = retire_age - current_age
    if years_to_retire <= 0: return

    annual_return = annual_return_pct / 100
    monthly_return = annual_return / 12
    months = years_to_retire * 12

    # חישוב מסלולים לגרף: קרן מול ריבית
    balances = []
    principals = []
    current_bal = balance
    current_principal = balance

    for m in range(months + 1):
        balances.append(current_bal)
        principals.append(current_principal)
        current_bal = current_bal * (1 + monthly_return) + monthly_dep
        current_principal += monthly_dep

    future_balance = balances[-1]
    projected_coefficient = manual_coefficient
    gross_pension_fund = future_balance / projected_coefficient
    national_insurance = 2300
    total_gross = gross_pension_fund + national_insurance

    taxable_income = max(0, gross_pension_fund - 4500)
    if taxable_income <= 6790: tax = taxable_income * 0.10
    elif taxable_income <= 9730: tax = (6790 * 0.10) + (taxable_income - 6790) * 0.14
    else: tax = (6790 * 0.10) + (2940 * 0.14) + (taxable_income - 9730) * 0.20

    tax = max(0, tax - 570)
    health_tax = 116
    net_pension = total_gross - tax - health_tax
    real_value_net = net_pension / ((1 + (inflation_pct / 100)) ** years_to_retire)

    # הדפסת נתונים מפורטת
    print("="*40)
    print(f" תמצית תחזית פרישה לגיל {retire_age}")
    print("="*40)
    print(f"צבירה צפויה בפרישה (נומינלי): {future_balance:,.0f} ₪")
    print(f"מקדם אקטוארי בשימוש: {projected_coefficient:.1f}")
    print(f"אינפלציה שנתית חזויה: {inflation_pct}%")
    print("-"*40)
    print(f"קצבת פנסיה (ברוטו): {gross_pension_fund:,.0f} ₪")
    print(f"קצבת ביטוח לאומי: {national_insurance:,.0f} ₪")
    print(f"מס הכנסה משוער: {tax:,.0f} ₪")
    print(f"דמי בריאות: {health_tax} ₪")
    print("-"*40)
    print(f"סה\"כ הכנסה נטו (נומינלי): {net_pension:,.0f} ₪")
    print(f"ערך ריאלי (כוח קנייה היום): {real_value_net:,.0f} ₪")
    print("="*40)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # גרף 1: צמיחת הון (קרן וריבית)
    years_arr = np.linspace(current_age, retire_age, len(balances))
    ax1.stackplot(years_arr, [principals, np.array(balances) - np.array(principals)],
                  labels=[fix_heb('קרן (הפקדות)'), fix_heb('ריבית (רווחים)')],
                  colors=['#4682B4', '#87CEEB'], alpha=0.7)
    ax1.set_title(fix_heb("צמיחת צבירה פנסיונית: קרן מול ריבית"))
    ax1.set_xlabel(fix_heb("גיל"))
    ax1.set_ylabel(fix_heb("סכום בצבירה ₪"))
    ax1.legend(loc='upper left')
    ax1.grid(True, linestyle='--', alpha=0.6)

    # גרף 2: התפלגות קצבה עם צבעים מותאמים
    labels = [fix_heb('נטו פנסיה'), fix_heb('ביטוח לאומי'), fix_heb('מס הכנסה'), fix_heb('דמי בריאות')]
    sizes = [gross_pension_fund - tax - health_tax, national_insurance, tax, health_tax]
    # צבעים: נטו (ברירת מחדל), ביטוח לאומי (תכלת), מס הכנסה (בורוד), דמי בריאות (כתום)
    colors = ['#99ff99', '#87CEEB', '#FFC0CB', '#FFA500']

    ax2.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=colors)
    ax2.set_title(fix_heb("התפלגות קצבה חודשית ברוטו"))

    plt.tight_layout()
    plt.show()

calculate_pension_colab(גיל_נוכחי, צבירה_קיימת, הפקדה_חודשית, תשואה_שנתית_אחוזים, אינפלציה_שנתית_חזויה, מקדם_אקטוארי_חזוי)

import matplotlib.pyplot as plt
import numpy as np
import arabic_reshaper
from bidi.algorithm import get_display

# פונקציית עזר לתיקון עברית בגרפים
def fix_heb(text):
    if not text: return text
    reshaped_text = arabic_reshaper.reshape(str(text))
    return get_display(reshaped_text)

# @markdown הכנס את הנתונים שלך כאן:
גיל_נוכחי = 46  # @param {type:"integer"}
צבירה_קיימת = 1800000  # @param {type:"number"}
הפקדה_חודשית = 7800  # @param {type:"number"}
תשואה_שנתית_אחוזים = 5  # @param {type:"number"}
אינפלציה_שנתית_חזויה = 1.9  # @param {type:"number"}
מקדם_אקטוארי_חזוי = 203.2 # @param {type:"number"}

def calculate_pension_colab(current_age, balance, monthly_dep, annual_return_pct, inflation_pct, manual_coefficient):
    retire_age = 67
    years_to_retire = retire_age - current_age
    if years_to_retire <= 0: return

    annual_return = annual_return_pct / 100
    monthly_return = annual_return / 12
    months = years_to_retire * 12

    # חישוב מסלולים לגרף: קרן מול ריבית
    balances = []
    principals = []
    current_bal = balance
    current_principal = balance

    for m in range(months + 1):
        balances.append(current_bal)
        principals.append(current_principal)
        current_bal = current_bal * (1 + monthly_return) + monthly_dep
        current_principal += monthly_dep

    future_balance = balances[-1]

    def get_net_pension(f_bal, coeff, infl_pct):
        gross_pension = f_bal / coeff
        ni = 2300
        total_g = gross_pension + ni
        taxable = max(0, gross_pension - 4500)
        if taxable <= 6790: t = taxable * 0.10
        elif taxable <= 9730: t = (6790 * 0.10) + (taxable - 6790) * 0.14
        else: t = (6790 * 0.10) + (2940 * 0.14) + (taxable - 9730) * 0.20
        t = max(0, t - 570)
        h_tax = 116
        net = total_g - t - h_tax
        real_net = net / ((1 + (infl_pct / 100)) ** years_to_retire)
        return net, t, gross_pension, ni, h_tax, real_net

    # נתוני המשתמש המקוריים
    net_pension, tax, gross_pension_fund, national_insurance, health_tax, real_value_net = get_net_pension(future_balance, manual_coefficient, inflation_pct)

    # הדפסת נתונים מפורטת
    print("="*40)
    print(f" תמצית תחזית פרישה לגיל {retire_age}")
    print("="*40)
    print(f"צבירה צפויה בפרישה (נומינלי): {future_balance:,.0f} ₪")
    print(f"מקדם אקטוארי בשימוש: {manual_coefficient:.1f}")
    print(f"אינפלציה שנתית חזויה: {inflation_pct}%")
    print("-"*40)
    print(f"קצבת פנסיה (ברוטו): {gross_pension_fund:,.0f} ₪")
    print(f"קצבת ביטוח לאומי: {national_insurance:,.0f} ₪")
    print(f"מס הכנסה משוער: {tax:,.0f} ₪")
    print(f"דמי בריאות: {health_tax} ₪")
    print("-"*40)
    print(f"\u05E1ה\"כ הכנסה נטו (נומינלי): {net_pension:,.0f} ₪")
    print(f"\u05E2רך ריאלי (כוח קנייה היום): {real_value_net:,.0f} ₪")
    print("="*40)

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(22, 6))

    # גרף 1: צמיחת הון
    years_arr = np.linspace(current_age, retire_age, len(balances))
    ax1.stackplot(years_arr, [principals, np.array(balances) - np.array(principals)],
                  labels=[fix_heb('קרן (הפקדות)'), fix_heb('ריבית (רווחים)')],
                  colors=['#4682B4', '#87CEEB'], alpha=0.7)
    ax1.set_title(fix_heb("צמיחת צבירה פנסיונית: קרן מול ריבית"))
    ax1.set_xlabel(fix_heb("גיל"))
    ax1.set_ylabel(fix_heb("סכום בצבירה ₪"))
    ax1.legend(loc='upper left')
    ax1.grid(True, linestyle='--', alpha=0.6)

    # גרף 2: התפלגות קצבה
    labels_pie = [fix_heb('נטו פנסיה'), fix_heb('ביטוח לאומי'), fix_heb('מס הכנסה'), fix_heb('דמי בריאות')]
    sizes = [gross_pension_fund - tax - health_tax, national_insurance, tax, health_tax]
    colors = ['#99ff99', '#87CEEB', '#FFC0CB', '#FFA500']
    ax2.pie(sizes, labels=labels_pie, autopct='%1.1f%%', startangle=140, colors=colors)
    ax2.set_title(fix_heb("התפלגות קצבה חודשית ברוטו"))

    # גרף 3: ניתוח רגישות (נטו ריאלי מול אינפלציה)
    inflations = np.linspace(1.5, 3.0, 10)
    coeffs = [200, 210, 215, 220]

    # הוספת המקדם של המשתמש להשוואה
    for c in coeffs:
        real_nets = [get_net_pension(future_balance, c, i)[5] for i in inflations]
        ax3.plot(inflations, real_nets, label=f"{fix_heb('מקדם')} {c}", alpha=0.6)

    # קו בולט עבור המקדם שהוכנס
    user_real_nets = [get_net_pension(future_balance, manual_coefficient, i)[5] for i in inflations]
    ax3.plot(inflations, user_real_nets, color='red', linewidth=3, linestyle='--', label=f"{fix_heb('המקדם שלך')}: {manual_coefficient}")

    ax3.axvline(x=inflation_pct, color='gray', linestyle=':', label=fix_heb('אינפלציה חזויה'))
    ax3.set_title(fix_heb("ניתוח רגישות: קצבה ריאלית מול אינפלציה"))
    ax3.set_xlabel(fix_heb("אינפלציה שנתית (%)"))
    ax3.set_ylabel(fix_heb("קצבה נטו ריאלית (מונחי היום) ₪"))
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

calculate_pension_colab(גיל_נוכחי, צבירה_קיימת, הפקדה_חודשית, תשואה_שנתית_אחוזים, אינפלציה_שנתית_חזויה, מקדם_אקטוארי_חזוי)


import matplotlib.pyplot as plt
import numpy as np
import arabic_reshaper
from bidi.algorithm import get_display

# פונקציית עזר לתיקון עברית בגרפים
def fix_heb(text):
    if not text: return text
    reshaped_text = arabic_reshaper.reshape(str(text))
    return get_display(reshaped_text)

# @markdown הכנס את הנתונים שלך כאן:
גיל_נוכחי = 46  # @param {type:"integer"}
צבירה_קיימת = 1800000  # @param {type:"number"}
הפקדה_חודשית = 7800  # @param {type:"number"}
תשואה_שנתית_אחוזים = 5.5  # @param {type:"number"}
אינפלציה_שנתית_חזויה = 1.9  # @param {type:"number"}
מקדם_אקטוארי_חזוי = 203.2 # @param {type:"number"}
דמי_בריאות_חודשיים = 237 # @param {type:"number"}
קצבת_ביטוח_לאומי = 2300 # @param {type:"number"}

def calculate_pension_colab(current_age, balance, monthly_dep, annual_return_pct, inflation_pct, manual_coefficient, health_tax_input, ni_benefit):
    retire_age = 67
    years_to_retire = retire_age - current_age
    if years_to_retire <= 0: return

    def get_trajectory(yield_pct):
        m_return = (yield_pct / 100) / 12
        months = years_to_retire * 12
        bals = [balance]
        prins = [balance]
        curr_bal = balance
        curr_prin = balance
        for _ in range(months):
            curr_bal = curr_bal * (1 + m_return) + monthly_dep
            curr_prin += monthly_dep
            bals.append(curr_bal)
            prins.append(curr_prin)
        return np.array(bals), np.array(prins)

    def get_net_pension(f_bal, coeff, infl_pct):
        gross_pension = f_bal / coeff
        ni = ni_benefit
        total_g = gross_pension + ni
        taxable = max(0, gross_pension - 4500)
        if taxable <= 6790: t = taxable * 0.10
        elif taxable <= 9730: t = (6790 * 0.10) + (taxable - 6790) * 0.14
        else: t = (6790 * 0.10) + (2940 * 0.14) + (taxable - 9730) * 0.20
        t = max(0, t - 570)
        h_tax = health_tax_input
        net = total_g - t - h_tax
        real_net = net / ((1 + (infl_pct / 100)) ** years_to_retire)
        return net, t, gross_pension, ni, h_tax, real_net

    # חישוב עבור התרחיש הנבחר
    user_balances, user_principals = get_trajectory(annual_return_pct)
    future_balance = user_balances[-1]
    net_pension, tax, gross_pension_fund, ni, health, real_val = get_net_pension(future_balance, manual_coefficient, inflation_pct)

    # הדפסת נתונים מפורטת
    print("="*40)
    print(f" תמצית תחזית פרישה לגיל {retire_age}")
    print("="*40)
    print(f"צבירה צפויה בפרישה (נומינלי): {future_balance:,.0f} ₪")
    print(f"מקדם אקטוארי בשימוש: {manual_coefficient:.1f}")
    print(f"אינפלציה שנתית חזויה: {inflation_pct}%")
    print("-"*40)
    print(f"קצבת פנסיה (ברוטו): {gross_pension_fund:,.0f} ₪")
    print(f"קצבת ביטוח לאומי: {ni:,.0f} ₪")
    print(f"מס הכנסה משוער: {tax:,.0f} ₪")
    print(f"דמי בריאות: {health} ₪")
    print("-"*40)
    print(f'סה"כ הכנסה נטו (נומינלי): {net_pension:,.0f} ₪')
    print(f"ערך ריאלי (כוח קנייה היום): {real_val:,.0f} ₪")
    print("="*40)

    fig, axes = plt.subplots(2, 2, figsize=(20, 14))
    (ax1, ax2), (ax3, ax4) = axes
    years_arr = np.linspace(current_age, retire_age, len(user_balances))

    # גרף 1: צמיחה עם רגישות לתשואה
    yield_range = np.arange(annual_return_pct - 1.5, annual_return_pct + 1.6, 0.5)
    for y in yield_range:
        bals, _ = get_trajectory(y)
        is_user = np.isclose(y, annual_return_pct)
        line, = ax1.plot(years_arr, bals / 1_000_000, label=f"{y:.1f}%", linewidth=3 if is_user else 1, alpha=0.8 if is_user else 0.4, color='teal' if is_user else 'gray', linestyle='-' if is_user else '--')
        ax1.text(years_arr[-1], bals[-1]/1_000_000, f" {y:.1f}%", color=line.get_color(), va='center', fontweight='bold' if is_user else 'normal')
        if is_user: ax1.fill_between(years_arr, bals / 1_000_000, color='teal', alpha=0.1)
    ax1.fill_between(years_arr, user_principals / 1_000_000, color='#4682B4', alpha=0.3, label=fix_heb('קרן (הפקדות)'))
    ax1.set_title(fix_heb("צמיחת צבירה: רגישות לתשואה והרכב קרן"))
    ax1.set_xlabel(fix_heb("גיל"))
    ax1.set_ylabel(fix_heb("סכום בצבירה (מליון ₪)"))
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)

    # גרף 2: התפלגות קצבה
    labels_pie = [fix_heb('נטו פנסיה'), fix_heb('ביטוח לאומי'), fix_heb('מס הכנסה'), fix_heb('דמי בריאות')]
    sizes_pie = [gross_pension_fund - tax - health, ni, tax, health]
    colors_pie = ['#99ff99', '#87CEEB', '#FFC0CB', '#FFA500']
    ax2.pie(sizes_pie, labels=labels_pie, autopct='%1.1f%%', startangle=140, colors=colors_pie)
    ax2.set_title(fix_heb("התפלגות קצבה חודשית ברוטו"))

    # גרף 3: רגישות לאינפלציה (לפי מקדם)
    inflations = np.linspace(1.5, 3.0, 10)
    coeffs = [200, 210, 215, 220]
    for c in coeffs:
        nets = [get_net_pension(future_balance, c, i)[5] for i in inflations]
        line, = ax3.plot(inflations, nets, label=f"{fix_heb('מקדם')} {c}", alpha=0.5)
        ax3.text(inflations[-1], nets[-1], f" {c}", color=line.get_color(), va='center')
    user_nets = [get_net_pension(future_balance, manual_coefficient, i)[5] for i in inflations]
    ax3.plot(inflations, user_nets, color='red', linewidth=3, linestyle='--', label=f"{fix_heb('המקדם שלך')}: {manual_coefficient}")
    ax3.text(inflations[-1], user_nets[-1], f" {manual_coefficient}", color='red', va='center', fontweight='bold')
    ax3.axvline(x=inflation_pct, color='black', linestyle=':', label=fix_heb('אינפלציה חזויה'))
    ax3.set_title(fix_heb("רגישות: קצבה ריאלית מול אינפלציה"))
    ax3.set_xlabel(fix_heb("אינפלציה שנתית (%)"))
    ax3.set_ylabel(fix_heb("קצבה נטו ריאלית ₪"))
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # גרף 4: קצבה ריאלית כתלות בתשואה (לפי אינפלציה)
    yield_range_fine = np.linspace(annual_return_pct - 1.5, annual_return_pct + 1.5, 20)
    infl_steps = np.arange(1.5, 3.1, 0.5)
    for inf in infl_steps:
        is_target_infl = np.isclose(inf, inflation_pct, atol=0.25)
        y_real_nets = []
        for y_pct in yield_range_fine:
             b_traj, _ = get_trajectory(y_pct)
             y_real_nets.append(get_net_pension(b_traj[-1], manual_coefficient, inf)[5])
        line, = ax4.plot(yield_range_fine, y_real_nets, label=f"{fix_heb('אינפלציה')} {inf}%", linewidth=3 if is_target_infl else 1, alpha=1 if is_target_infl else 0.5)
        ax4.text(yield_range_fine[-1], y_real_nets[-1], f" {inf}%", color=line.get_color(), va='center', fontweight='bold' if is_target_infl else 'normal')

    ax4.axvline(x=annual_return_pct, color='black', linestyle='--', label=fix_heb('התשואה שלך'))
    ax4.set_title(fix_heb("רגישות: קצבה ריאלית מול תשואה (לפי אינפלציה)"))
    ax4.set_xlabel(fix_heb("תשואה שנתית (%)"))
    ax4.set_ylabel(fix_heb("קצבה נטו ריאלית ₪"))
    ax4.legend()
    ax4.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

calculate_pension_colab(גיל_נוכחי, צבירה_קיימת, הפקדה_חודשית, תשואה_שנתית_אחוזים, אינפלציה_שנתית_חזויה, מקדם_אקטוארי_חזוי, דמי_בריאות_חודשיים, קצבת_ביטוח_לאומי)

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import arabic_reshaper
from bidi.algorithm import get_display

# תצורה בסיסית של העמוד
#st.set_page_config(page_title="מחשבון פנסיה מתקדם", layout="wide")

# פונקציית עזר לתיקון עברית בגרפים
def fix_heb(text):
    if not text: return text
    reshaped_text = arabic_reshaper.reshape(str(text))
    return get_display(reshaped_text)

st.title("מחשבון פנסיה מתקדם - פרישה בגיל 67")

# יצירת סרגל צד להזנת נתונים
with st.sidebar:
    st.header("נתוני כניסה")
    גיל_נוכחי = st.number_input("גיל נוכחי", value=46)
    צבירה_קיימת = st.number_input("צבירה קיימת (₪)", value=1800000)
    הפקדה_חודשית = st.number_input("הפקדה חודשית (₪)", value=7800)
    תשואה_שנתית_אחוזים = st.slider("תשואה שנתית (%) ", 0.0, 10.0, 5.5)
    אינפלציה_שנתית_חזויה = st.slider("אינפלציה שנתית (%) ", 0.0, 5.0, 1.9)
    מקדם_אקטוארי_חזוי = st.number_input("מקדם אקטוארי", value=203.2)
    דמי_בריאות_חודשיים = st.number_input("דמי בריאות (₪)", value=237)
    קצבת_ביטוח_לאומי = st.number_input("קצבת ביטוח לאומי (₪)", value=2300)

# פונקציית החישוב המרכזית
def calculate_pension(current_age, balance, monthly_dep, annual_return_pct, inflation_pct, manual_coefficient, health_tax_input, ni_benefit):
    retire_age = 67
    years_to_retire = retire_age - current_age
    if years_to_retire <= 0:
        st.error("הגיל חייב להיות נמוך מגיל הפרישה")
        return

    def get_trajectory(yield_pct):
        m_return = (yield_pct / 100) / 12
        months = years_to_retire * 12
        bals = [balance]
        prins = [balance]
        curr_bal = balance
        curr_prin = balance
        for _ in range(months):
            curr_bal = curr_bal * (1 + m_return) + monthly_dep
            curr_prin += monthly_dep
            bals.append(curr_bal)
            prins.append(curr_prin)
        return np.array(bals), np.array(prins)

    def get_net_pension(f_bal, coeff, infl_pct):
        gross_pension = f_bal / coeff
        total_g = gross_pension + ni_benefit
        taxable = max(0, gross_pension - 4500)
        if taxable <= 6790: t = taxable * 0.10
        elif taxable <= 9730: t = (6790 * 0.10) + (taxable - 6790) * 0.14
        else: t = (6790 * 0.10) + (2940 * 0.14) + (taxable - 9730) * 0.20
        t = max(0, t - 570)
        net = total_g - t - health_tax_input
        real_net = net / ((1 + (infl_pct / 100)) ** years_to_retire)
        return net, t, gross_pension, ni_benefit, health_tax_input, real_net

    user_balances, user_principals = get_trajectory(annual_return_pct)
    future_balance = user_balances[-1]
    net_pension, tax, gross_pension_fund, ni, health, real_val = get_net_pension(future_balance, manual_coefficient, inflation_pct)

    # הצגת נתונים ב-Streamlit
    col1, col2, col3 = st.columns(3)
    col1.metric("צבירה בפרישה (נומינלי)", f"{future_balance:,.0f} ₪")
    col2.metric("קצבת נטו חודשית", f"{net_pension:,.0f} ₪")
    col3.metric("ערך ריאלי (כוח קנייה היום)", f"{real_val:,.0f} ₪")

    st.markdown("---")
    st.subheader("ניתוח ויזואלי")

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    (ax1, ax2), (ax3, ax4) = axes
    years_arr = np.linspace(current_age, retire_age, len(user_balances))

    # גרף 1: צמיחה
    yield_range = np.arange(annual_return_pct - 1.5, annual_return_pct + 1.6, 0.5)
    for y in yield_range:
        bals, _ = get_trajectory(y)
        is_user = np.isclose(y, annual_return_pct)
        line, = ax1.plot(years_arr, bals / 1_000_000, label=f"{y:.1f}%", linewidth=3 if is_user else 1, alpha=0.8 if is_user else 0.4, color='teal' if is_user else 'gray')
        ax1.text(years_arr[-1], bals[-1]/1_000_000, f" {y:.1f}%", color=line.get_color(), va='center', fontweight='bold' if is_user else 'normal')
        if is_user: ax1.fill_between(years_arr, bals / 1_000_000, color='teal', alpha=0.1)
    ax1.fill_between(years_arr, user_principals / 1_000_000, color='#4682B4', alpha=0.3, label=fix_heb('קרן (הפקדות)'))
    ax1.set_title(fix_heb("צמיחת צבירה: רגישות לתשואה והרכב קרן"))
    ax1.set_ylabel(fix_heb("מליון ₪"))
    ax1.legend(loc='upper left')

    # גרף 2: עוגה
    labels_pie = [fix_heb('נטו פנסיה'), fix_heb('ביטוח לאומי'), fix_heb('מס הכנסה'), fix_heb('דמי בריאות')]
    sizes_pie = [gross_pension_fund - tax - health, ni, tax, health]
    ax2.pie(sizes_pie, labels=labels_pie, autopct='%1.1f%%', startangle=140, colors=['#99ff99', '#87CEEB', '#FFC0CB', '#FFA500'])
    ax2.set_title(fix_heb("התפלגות קצבה חודשית ברוטו"))

    # גרף 3: אינפלציה
    inflations = np.linspace(1.5, 3.0, 10)
    for c in [200, 210, 215, 220]:
        nets = [get_net_pension(future_balance, c, i)[5] for i in inflations]
        line, = ax3.plot(inflations, nets, label=f"{fix_heb('מקדם')} {c}", alpha=0.5)
        ax3.text(inflations[-1], nets[-1], f" {c}", color=line.get_color(), va='center')
    user_nets = [get_net_pension(future_balance, manual_coefficient, i)[5] for i in inflations]
    ax3.plot(inflations, user_nets, color='red', linewidth=3, linestyle='--')
    ax3.axvline(x=inflation_pct, color='black', linestyle=':')
    ax3.set_title(fix_heb("רגישות: קצבה ריאלית מול אינפלציה"))

    # גרף 4: תשואה
    yield_range_fine = np.linspace(annual_return_pct - 1.5, annual_return_pct + 1.5, 20)
    for inf in [1.5, 2.0, 2.5, 3.0]:
        is_target = np.isclose(inf, inflation_pct, atol=0.25)
        y_real_nets = [get_net_pension(get_trajectory(y_pct)[0][-1], manual_coefficient, inf)[5] for y_pct in yield_range_fine]
        line, = ax4.plot(yield_range_fine, y_real_nets, label=f"{inf}%", linewidth=3 if is_target else 1)
        ax4.text(yield_range_fine[-1], y_real_nets[-1], f" {inf}%", color=line.get_color(), va='center')
    ax4.axvline(x=annual_return_pct, color='black', linestyle='--')
    ax4.set_title(fix_heb("רגישות: קצבה ריאלית מול תשואה (לפי אינפלציה)"))

    plt.tight_layout()
    st.pyplot(fig)

# הפעלה
calculate_pension(גיל_נוכחי, צבירה_קיימת, הפקדה_חודשית, תשואה_שנתית_אחוזים, אינפלציה_שנתית_חזויה, מקדם_אקטוארי_חזוי, דמי_בריאות_חודשיים, קצבת_ביטוח_לאומי)


import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
# שים לב: באפליקציית WEB חיצונית מומלץ להשתמש בגופנים שתומכים בעברית מובנית במקום arabic_reshaper אם אפשר

#st.title("מחשבון פנסיה מתקדם")

# יצירת סרגל צד לנתונים
#with st.sidebar:
#    st.header("נתוני כניסה")
#    current_age = st.number_input("גיל נוכחי", value=46, key=1)
#    balance = st.number_input("צבירה קיימת", value=1800000, key=2)
#    monthly_dep = st.number_input("הפקדה חודשית", value=7800, key=3)
    # ... שאר הפרמטרים באותו אופן

# כאן מכניסים את הלוגיקה של הפונקציה calculate_pension_colab
# ובמקום plt.show() משתמשים ב-st.pyplot(fig)
